name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Backend:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: ["macOS", "Linux"]
        include:
          - name: "macOS"
            os: "macos-latest"
          
          - name: "Linux"
            os: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build Backend
      run: >
        cd Backend
        swift build -c release
        
  App:
    runs-on: ${{ matrix.os }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer
    strategy:
      fail-fast: false
      matrix:
        name: ["macOS"]
        include:
          - name: "macOS"
            os: "macos-latest"
            
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build App
      run: >
          xcodebuild \
            -workspace "Auth.xcworkspace" \
            -scheme "Auth" \
            -destination "platform=iOS Simulator,OS=16.0,name=iPhone 13 Pro" \
            ONLY_ACTIVE_ARCH=NO || exit 1
        
