name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Build:
    runs-on: [ macos-latest, ubuntu-latest ]
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: swift build -c release
