name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: ["macOS", "Linux"]
        include:
          - name: "macOS"
            os: "macos-latest"
          
          - name: "Linux"
            os: "ubuntu-latest"
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build and Test
      run: swift build -c release
